### ISSUE TITLE
Fix the cases and deaths by date

### ISSUE THREAD

**Issue by WorldometersActiveCases** [Sandbird/covid19-Greece#7] opened 2023-12-14 09:10 UTC
[cases-greece-fixed.csv](https://github.com/Sandbird/covid19-Greece/files/13671028/cases-greece-fixed.csv)
You have to fix cases and deaths by date now. For example:
From November 13 to November 19, 2023: 7792 cases and 29 deaths, you have to put it at 2023-11-19
From November 20 to November 26, 2023: 8299 cases and 46 deaths, you have to put it at 2023-11-26
From November 27 to December 3, 2023: 9842 cases and 44 deaths, you have to put it at 2023-12-03

**Comment by Sandbird** [comment] 2023-12-14 11:17
As I mentioned earlier, you need the **cases_weekly_ecdc.csv** file.
![Screenshot_1](https://github.com/Sandbird/covid19-Greece/assets/204934/fc2ada03-1617-4bee-88eb-ee8b78d05ad7)

The c**ases.csv** file is used to hold values (in the old daily format) for the Greek NPHO reports, which are released every Thursday (https://eody.gov.gr/en). Once that is completed, and when ECDC reports the latest changes, the correct and updated values are recorded in the cases_weekly_ecdc.csv file.

**Comment by WorldometersActiveCases** [comment] 2023-12-15 01:33
You have to fix at the page:
https://github.com/Sandbird/covid19-Greece/blob/master/cases.csv

**Comment by Sandbird** [comment] 2023-12-15 09:11
cases.csv was intended for the daily reports. Hoping that the daily report would resume at some point, I continued updating it. Subsequently, all of these values were transferred to the cases_weekly_ecdc.csv file and I can't make significant changes to cases.csv as other people are still using it.
Why cant you use cases_weekly_ecdc instead? Please explain.

**Comment by WorldometersActiveCases** [comment] 2023-12-17 16:10
Add cases from 4 December to 10 December please:
https://www.covidstats.gr/eody.html

**Comment by Sandbird** [comment] 2023-12-17 17:31
They are not out yet. We only have the cases+reinfections values from the Greek NPHO (28.539), but ECDC hasn't updated their dataset (https://github.com/EU-ECDC/Respiratory_viruses_weekly_data/tree/main/data/snapshots) yet, which includes ONLY the cases. I can't just add 28.539 cases...it's wrong. Need to separate the 2 totals.
It's not that I am slacking, I've already sent 2 messages to ECDC and raised one issue ticket at their new github repo (https://github.com/EU-ECDC/Respiratory_viruses_weekly_data/issues/1).

This whole thing is a mess....doing the best I can to keep an up-to-date database.

**Comment by WorldometersActiveCases** [comment] 2023-12-18 11:06
How about this page?
https://eody.gov.gr/evdomadiaia-ekthesi-epidimiologikis-epitirisis-anapneystikon-loimoxeon-49-2023/

**Comment by Sandbird** [comment] 2023-12-18 11:59
Yes, this is the weekly GR report. 
181.775 PCR/Rapid weekly tests with 15.7% positivity rate = 28,539 cases.
But these are not the cases they report to TESSy and these are not the cases that ECDC reports every week.
These are the cases+reinfections. IF ECDC (because they stopped updating their last dashboard/dataset, and now they have erviss.org) doesn't update their latest erviss database anymore, I will be forced to use that number, yes. If that's the case, then every Thursday (when the GR report comes out, I'll be updating the db), but up until now ECDC was releasing their dataset on Fridays or worst case scenario Mondays which included corrections for cases & deaths on previous weeks as well.....which we'll be losing now if they stop updating their new dataset.

![image](https://github.com/Sandbird/covid19-Greece/assets/204934/1cb589f5-0a7c-4f02-a8d3-2336abc85d0e)

**Comment by Sandbird** [comment] 2023-12-18 17:22
ECDC just updated their data, i've updated the repo

**Closed** 2023-12-21 15:13 UTC
